# Site settings
title: Rodolfo's blog
email: rodolfo.3@gmail.com
description: "Random experiments..."
baseurl: ""
staticurl: "/static"
rooturl: "/"
url: "http://blog.rodolfo.pro.br"
author: Rodolfo Stangherlin

email: blog@rodolfo.pro.br
github_issue: https://github.com/rodolfo3/blog/issues/new

# Build settings
markdown: redcarpet
permalink: pretty

highlighter: pygments
