# Site settings
title: Rodolfo's blog
email: rodolfo.3@gmail.com
description: "Random experiments..."
baseurl: ""
rooturl: "/"
url: "http://blog.rodolfo.pro.br"
author: Rodolfo Stangherlin

# Build settings
markdown: kramdown
permalink: pretty

pygments: true

