# Site settings
title: Rodolfo's blog
email: rodolfo.3@gmail.com
description: "Random experiments..."
baseurl: ""
url: "http://blog.rodolfo.pro.br"

# Build settings
markdown: kramdown
permalink: pretty
